import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

export const metadata = {
  title: 'Akasha Khan',
  description: 'Generated by Akasha Khan',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <div className='mt-20'>
            <Header />
            { children }
        </div>
      </body>
    </html>
  )
}
